import food from "../images/caro-food.png";
import delivery from ".././images/deliver.png";
import fruits from ".././images/fruits.png";
import likes from ".././images/likes.png";
import vegetable from ".././images/vegetable.png";
import diet from ".././images/diet.png";

export const product = [
  {
    img: food,
    name: "Lunch",
    info: "Chicken fricassee with mushrooms and bulgur",
    protain: "15 g",
    Fat: "7 g",
    Carbohydrates: "24 g",
    Energy: "285 kсal",
    total: "weight: 345 g",
  },
  {
    img: food,
    name: "Lunch",
    info: "Chicken fricassee with mushrooms and bulgur",
    protain: "15 g",
    Fat: "7 g",
    Carbohydrates: "24 g",
    Energy: "285 kсal",
    total: "weight: 345 g",
  },
  {
    img: food,
    name: "Lunch",
    info: "Chicken fricassee with mushrooms and bulgur",
    protain: "15 g",
    Fat: "7 g",
    Carbohydrates: "24 g",
    Energy: "285 kсal",
    total: "weight: 345 g",
  },
  {
    img: food,
    name: "Lunch",
    info: "Chicken fricassee with mushrooms and bulgur",
    protain: "15 g",
    Fat: "7 g",
    Carbohydrates: "24 g",
    Energy: "285 kсal",
    total: "weight: 345 g",
  },
  {
    img: food,
    name: "Lunch",
    info: "Chicken fricassee with mushrooms and bulgur",
    protain: "15 g",
    Fat: "7 g",
    Carbohydrates: "24 g",
    Energy: "285 kсal",
    total: "weight: 345 g",
  },
  {
    img: food,
    name: "Lunch",
    info: "Chicken fricassee with mushrooms and bulgur",
    protain: "15 g",
    Fat: "7 g",
    Carbohydrates: "24 g",
    Energy: "285 kсal",
    total: "weight: 345 g",
  },
  {
    img: food,
    name: "Lunch",
    info: "Chicken fricassee with mushrooms and bulgur",
    protain: "15 g",
    Fat: "7 g",
    Carbohydrates: "24 g",
    Energy: "285 kсal",
    total: "weight: 345 g",
  },
  {
    img: food,
    name: "Lunch",
    info: "Chicken fricassee with mushrooms and bulgur",
    protain: "15 g",
    Fat: "7 g",
    Carbohydrates: "24 g",
    Energy: "285 kсal",
    total: "weight: 345 g",
  },
  {
    img: food,
    name: "Lunch",
    info: "Chicken fricassee with mushrooms and bulgur",
    protain: "15 g",
    Fat: "7 g",
    Carbohydrates: "24 g",
    Energy: "285 kсal",
    total: "weight: 345 g",
  },
  {
    img: food,
    name: "Lunch",
    info: "Chicken fricassee with mushrooms and bulgur",
    protain: "15 g",
    Fat: "7 g",
    Carbohydrates: "24 g",
    Energy: "285 kсal",
    total: "weight: 345 g",
  },
  {
    img: food,
    name: "Lunch",
    info: "Chicken fricassee with mushrooms and bulgur",
    protain: "15 g",
    Fat: "7 g",
    Carbohydrates: "24 g",
    Energy: "285 kсal",
    total: "weight: 345 g",
  },
  {
    img: food,
    name: "Lunch",
    info: "Chicken fricassee with mushrooms and bulgur",
    protain: "15 g",
    Fat: "7 g",
    Carbohydrates: "24 g",
    Energy: "285 kсal",
    total: "weight: 345 g",
  },
  {
    img: food,
    name: "Lunch",
    info: "Chicken fricassee with mushrooms and bulgur",
    protain: "15 g",
    Fat: "7 g",
    Carbohydrates: "24 g",
    Energy: "285 kсal",
    total: "weight: 345 g",
  },
  {
    img: food,
    name: "Lunch",
    info: "Chicken fricassee with mushrooms and bulgur",
    protain: "15 g",
    Fat: "7 g",
    Carbohydrates: "24 g",
    Energy: "285 kсal",
    total: "weight: 345 g",
  },
  {
    img: food,
    name: "Lunch",
    info: "Chicken fricassee with mushrooms and bulgur",
    protain: "15 g",
    Fat: "7 g",
    Carbohydrates: "24 g",
    Energy: "285 kсal",
    total: "weight: 345 g",
  },
];
export const week = [
  { name: "Monday" },
  { name: "Tuesday" },
  { name: "Wednesday" },
  { name: "Thursday" },
  { name: "Friday" },
  { name: "Saturday" },
  { name: "Sunday" },
];

export const advantages = [
  {
    img: delivery,
    info: "We'll deliver it free of charge",
    abo: "In a convenient 2-hour interval",
  },
  {
    img: fruits,
    info: "We’ll calculate calories",
    abo: "It will be easy for you to control your diet",
  },
  {
    img: likes,
    info: "We'll help you to save up to 20 hours ",
    abo: "of free time a week for you",
  },
  {
    img: vegetable,
    info: "Everything is ready, just warm it up",
    abo: "We’ll bring you ready-made dishes",
  },
  {
    img: diet,
    abo: "Lorem ipsum dolor sit amet consectetur. Quisque sed nisi turpis enim. Amet blandit ut.",
  },
];
